version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  nats-streaming:
    image: nats-streaming:latest
    container_name: "nats-streaming"
    ports:
      - 4222:4222
      - 8222:8222
  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - 6379:6379