version: '3'
services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: hermes
    restart: always
    environment:
     - SQLHost=percona
    ports:
     - "32901:9044"
    command: ["/app"]